### ISSUE TITLE
Conflicting Training and training.

### ISSUE THREAD

**Issue by mydavids** [boniface/hworkapi#52]
Hey,

Just making you aware that having a folder "Training" with Gavin's repositories and having a "training" folder with SONY's repositories is causing some weird issue for me in Windows where on github it displays both folders but on my local it shows only one folder and the files are constantly trying to overwrite each other. 

I understand that you're working on LINUX so you most likely won't have these issues but it's making things a bit messy on my end and I'm sure the same goes for anybody using Windows as their OS.

If you could kindly just remove the training folder with the repositories created by SONY, it should be fine. 

Thanks
Yusiry

@boniface  @gavin24 @TedVDM @bloma @louisane006 @lltsipa @mpisanel

**Comment by boniface** [comment]
Training package Repositories  had a ton of errors and was thinking of getting rid of it. I have not had a chance to review it and will have another look at it this evening 
@gavin24 @TedVDM @bloma @louisane006 @lltsipa   @mpisanel  @mydavids
